image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Selenium Grid
    init: |
      docker run -d -p 4444:4444 --name selenium-hub selenium/hub
      docker run -d --link selenium-hub:hub selenium/node-chrome
      docker run -d --link selenium-hub:hub selenium/node-chrome
    command: python scraper.py
